#!/usr/bin/env python3
import subprocess
import os
import sys
import re
from clang.cindex import Index, Config, CursorKind

# -------------------------------------------------------
# Auto-detect libclang installed via Homebrew
# -------------------------------------------------------
try:
    llvm_prefix = subprocess.check_output(
        ["brew", "--prefix", "llvm"], text=True
    ).strip()
except Exception:
    print("ERROR: Cannot run `brew --prefix llvm`.", file=sys.stderr)
    sys.exit(1)

libclang_path = os.path.join(llvm_prefix, "lib", "libclang.dylib")
if not os.path.exists(libclang_path):
    print(f"ERROR: libclang not found at {libclang_path}", file=sys.stderr)
    sys.exit(1)

Config.set_library_file(libclang_path)

# -------------------------------------------------------
# Input file
# -------------------------------------------------------
if len(sys.argv) < 2:
    print("Usage: python generate_flat_context.py mainTROLL4.0.cpp", file=sys.stderr)
    sys.exit(1)

SOURCE = sys.argv[1]
if not os.path.exists(SOURCE):
    print(f"ERROR: source file not found: {SOURCE}", file=sys.stderr)
    sys.exit(1)


# -------------------------------------------------------
# Utility to turn clang's "T[N]" into valid "T name[N]"
# -------------------------------------------------------
array_regex = re.compile(r"^(.*)\[(\d+)\]$")


def declare(type_spelling, name):
    """
    Convert clang's abstract type spelling into valid C++.
    Cases:
        "char[256]"              -> "char name[256]"
        "int[3]"                 -> "int name[3]"
        "unsigned short *[3]"    -> "unsigned short * name[3]"
        "float **"               -> "float ** name"
        "vector<float>"          -> "std::vector<float> name"
    """

    t = type_spelling.strip()

    # 1. vector<float> → std::vector<float>
    if t.startswith("vector<"):
        t = "std::" + t

    # 2. Handle array types T[N]
    m = array_regex.match(t)
    if m:
        base_t, size = m.group(1).strip(), m.group(2)
        return f"{base_t} {name}[{size}]"

    # 3. If pointer array like "unsigned short *[3]"
    # clang emits it as "*[3]" so detect this:
    if "*[" in t:
        base, arr = t.split("*", 1)
        m2 = re.match(r"^\[(\d+)\]$", arr.strip())
        if m2:
            size = m2.group(1)
            return f"{base.strip()} *{name}[{size}]"

    # 4. Normal scalar or pointer
    return f"{t} {name}"


# -------------------------------------------------------
# Collect globals
# -------------------------------------------------------
globals_found = []


def walk(node):
    for c in node.get_children():
        if (
            c.kind == CursorKind.VAR_DECL
            and c.semantic_parent is not None
            and c.semantic_parent.kind == CursorKind.TRANSLATION_UNIT
        ):
            globals_found.append(c)
        walk(c)


# Parse translation unit
index = Index.create()
tu = index.parse(SOURCE, args=["-std=c++17"])
if not tu:
    print("ERROR: Unable to parse file.", file=sys.stderr)
    sys.exit(1)

walk(tu.cursor)

# -------------------------------------------------------
# Emit struct
# -------------------------------------------------------
print("// ================================================================")
print("//  AUTO-GENERATED BY generate_flat_context.py")
print("//  DO NOT EDIT BY HAND — REGENERATE AFTER ANY GLOBAL CHANGES")
print("// ================================================================")
print("#include <vector>\n")
print("struct FlatContext {")

for g in globals_found:
    raw_t = g.type.spelling
    name = g.spelling

    loc = f"{g.location.file}:{g.location.line}" if g.location.file else "(unknown)"
    decl = declare(raw_t, name)

    print(f"    {decl};   // {loc}")

print("};")
